### ISSUE TITLE
Wraith compare or capture commands not working

### ISSUE THREAD

**Issue by pgauthamraju** [andrewccadman/wraith-selenium#11]
I get the following errors
D:\Automation\wraith>wraith compare configs/capture.yaml
COMPARING IMAGES
Process.fork is not supported by this Ruby
Comparing shots/login/320_current.png and shots/login/320_new.png
D:/Software/Ruby23-x64/lib/ruby/2.3.0/open3.rb:199:in `spawn': No such file or directory - compare -dissimilarity-threshold 1 -fuzz 20% -metric AE -highlight-color blue shots/login/320_current
.png shots/login/320_new.png shots/login/320_diff.png (Errno::ENOENT)
        from D:/Software/Ruby23-x64/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
        from D:/Software/Ruby23-x64/lib/ruby/2.3.0/open3.rb:95:in `popen3'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wraith-4.0.1/lib/wraith/compare_images.rb:35:in `compare_task'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wraith-4.0.1/lib/wraith/compare_images.rb:22:in `block in compare_images'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:484:in `call_with_index'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:318:in `block in work_direct'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:493:in `with_instrumentation'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:317:in `work_direct'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:260:in `map'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:217:in `each'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wraith-4.0.1/lib/wraith/compare_images.rb:18:in `compare_images'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wraith-4.0.1/lib/wraith/cli.rb:96:in `block in compare_images'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wraith-4.0.1/lib/wraith/helpers/utilities.rb:4:in `within_acceptable_limits'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wraith-4.0.1/lib/wraith/cli.rb:93:in `compare_images'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wraith-4.0.1/bin/wraith:5:in `<top (required)>'
        from D:/Software/Ruby23-x64/bin/wraith:22:in `load'
        from D:/Software/Ruby23-x64/bin/wraith:22:in `<main>'

D:\Automation\wraith>wraith capture configs/capture.yaml
Invalid drive specification.
D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wraith-4.0.1/lib/wraith/helpers/utilities.rb:56:in `run_command_safely': undefined method `chomp' for nil:NilClass (NoMethodError)
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wraith-4.0.1/lib/wraith/helpers/utilities.rb:37:in `list_debug_information'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wraith-4.0.1/lib/wraith/validate.rb:14:in `validate'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wraith-4.0.1/lib/wraith/cli.rb:121:in `block in capture'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wraith-4.0.1/lib/wraith/helpers/utilities.rb:4:in `within_acceptable_limits'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wraith-4.0.1/lib/wraith/cli.rb:120:in `capture'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from D:/Software/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wraith-4.0.1/bin/wraith:5:in `<top (required)>'
        from D:/Software/Ruby23-x64/bin/wraith:22:in `load'
        from D:/Software/Ruby23-x64/bin/wraith:22:in `<main>'

D:\Automation\wraith>phantomjs -v
1.9.8

**Comment by pgauthamraju** [comment]
I had similar problem 6 months back and ruby 2.0 and phantomjs 1.9.8 worked for me.  I was trying to setup in my new machine with latest versions and i see these errors. Now ruby 2.0 doesn't allow me to install wraith
